import React from "react";
import './Imprint.scss'

export default class Imprint extends React.Component {
    render() {
        return (
            <section className='imprint centered'>
                <div className="imprint-content">
                    <h1 className='sectionHeading'>Impressum</h1>
                    <p>
                        <b>Anbieter:</b><br/>
                        <br/>
                        Axel Springer Ideas Engineering<br/>
                        Axel-Springer-Straße 65<br/>
                        10888 Berlin<br/>
                        <br/>
                        <b>Kontakt:</b><br/>
                        <br/>
                        Telefon: 030/2591 78100<br/>
                        E-Mail: hello@asideas.de<br/>
                        <br/>
                        <br/>
                        <b>Verantwortlich für den Inhalt nach § 6 Abs.2 MDStV:</b><br/>
                        <br/>
                        Michael Alber<br/>
                        COO<br/>
                        Axel-Springer-Straße 65<br/>
                        10888 Berlin<br/>
                        <br/>
                        Amtsgericht/ Handelsregister<br/>
                        Sitz Berlin, Amtsgericht Charlottenburg, HRB 138466 B<br/>
                        USt-IdNr. DE 287499537<br/>
                        Geschäftsführer: Samir Fadlallah, Michael Alber<br/>
                    </p>
                </div>
                <div className="imprint-content">
                    <h1 className='sectionHeading'>Urheberrecht</h1>
                    <p>Copyright 2018 Axel Springer Ideas Engineering GmbH. Alle Rechte vorbehalten. Alle Inhalte (Texte, Bilder, Grafiken, Sound, Animationen und Videos) sowie deren Anordnung auf der Website der Axel Springer Axel Springer Ideas Engineering GmbH unterliegen dem Schutz des Urheberrechtsgesetzes und anderer Schutzgesetze. Die Inhalte dürfen nur im Rahmen der Schrankenbestimmungen des Urheberrechtsgesetzes vorbehaltlich weiterer anwendbarer Gesetze ohne vorherige schriftliche Zustimmung der Axel Springer SE genutzt werden.</p>


                    <h1 className='sectionHeading'>Datenschutzerklärung Axel Springer Ideas Engineering GmbH</h1>
                    <p>Wir freuen uns sehr über Ihr Interesse an Axel Springer Ideas Engineering GmbH. Um Axel Springer Ideas Engineering GmbH anbieten zu können, benötigen wir natürlich auch einige Daten über Sie. Dabei nehmen wir den Schutz personenbezogener Daten sehr ernst und verarbeiten diese stets im Einklang mit den anwendbaren datenschutzrechtlichen Bestimmungen, insbesondere der EU Datenschutz-Grundverordnung. Mit dieser Datenschutzerklärung möchten wir Sie vollumfänglich über Art, Umfang und Zweck der von uns verarbeiteten personenbezogenen Daten und Ihre Rechte als betroffene Person informieren.</p>
                    <h2>1. Verantwortlicher und allgemeine Hinweise</h2>
                    <p>Ihre Daten werden durch die Axel Springer SE, Axel-Springer-Str. 65, 10888 Berlin, Telefon: +49 30 2591 0, E-Mail: information@axelspringer.de verarbeitet (Diensteanbieter im Sinne des Telemediengesetzes (TMG) und Verantwortlicher im Sinne der Datenschutz-Grundverordnung (DSGVO). Diese meinen wir auch, wenn wir Formulierungen wie "wir" oder "uns" benutzen. Unter "Axel Springer Ideas Engineering GmbH" verstehen wir in diesem Dokument http://axelspringerideas.de/, jeweils inklusive aller dort verfügbaren Unterseiten, Inhalte und Funktionen (z. B. Internet-Foren, Gewinnspiele). Einzelne Teile von Axel Springer Ideas Engineering GmbH werden im Folgenden auch als "Onlinedienste" bezeichnet. Diese meinen wir auch, soweit nachfolgend von einer Website die Rede ist.</p>
                    <p>Unsere Services sind für die allgemeine Öffentlichkeit und nicht für Kinder gedacht. Wir erheben wissentlich keine personenbezogenen Daten von Nutzern, die gemäß der jeweiligen nationalen Gesetzgebung als Kinder gelten.</p>
                    <h2>2. Erhebung und Verarbeitung personenbezogener Daten</h2>
                    <p>In der Regel können Sie Onlinedienste, für die keine Bezahlung oder Registrierung erforderlich ist, ohne Angabe personenbezogener Daten nutzen. In bestimmten Fällen verarbeiten wir jedoch die in Ziffer 3. aufgelisteten personenbezogenen Daten. Dies geschieht grundsätzlich nur, soweit dies zur Bereitstellung einer funktionsfähigen Website sowie unserer Inhalte und Leistungen erforderlich. Ferner verarbeiten wir personenbezogene Daten im Zusammenhang mit der Nutzung von Axel Springer Ideas Engineering GmbH, wenn Sie diese von sich aus angeben, z. B. im Rahmen einer Registrierung, eines Gewinnspieles, einer Anfrage an uns, einer Bewerbung oder beim Abschluss eines Abonnements oder weil hierfür eine andere Rechtsgrundlage vorliegt (siehe Ziffer 4.). Sollten Sie dies nicht wünschen, können Sie unsere Dienste leider nicht oder nicht in vollem Umfang in Anspruch nehmen.</p>
                    <h2>3. Kategorien verarbeiteter Daten</h2>
                    <p>Sobald Sie Axel Springer Ideas Engineering GmbH nutzen, erfasst unser System automatisiert Informationen vom Computersystem des aufrufenden Rechners. Dabei können u. a. die folgenden Daten erhoben werden:</p>
                    <p>- Informationen über den Browsertyp und die verwendete Version</p>
                    <p>- Betriebssystem des Nutzers</p>
                    <p>- Datum und Uhrzeit des Zugriffs</p>
                    <p>- Webanalysedaten / pseudonyme Nutzungsprofile (Cookie ID, Ad ID etc.)</p>
                    <p>- Websites, von denen der Nutzer auf unsere Website gelangt</p>
                    <p>- Websites, die der Nutzer über unsere Website aufruft</p>
                    <p>Darüber hinaus verarbeiten wir die folgenden personenbezogenen Daten sofern ein Vertragsverhältnis zwischen Ihnen und uns besteht oder Sie die Daten anderweitig an uns übermittelt haben:</p>
                    <p>- Kommentare, Beiträge u.ä.</p>
                    <h2>4. Rechtsgrundlage und Zwecke der Verarbeitung</h2>
                    <p>Wir verarbeiten Ihre Daten ausschließlich aufgrund einer oder mehrerer der möglichen gesetzlichen Grundlagen.</p>
                    <p>Gemäß DSGVO können personenbezogene Daten insbesondere aufgrund eines Vertrages oder zur Durchführung vorvertraglicher Maßnahmen, bei Vorliegen einer Einwilligung, aufgrund eines berechtigten Interesses oder eines Gesetzes sowie zum Schutz lebenswichtiger oder öffentlicher Interessen verarbeitet werden.</p>
                    <p>Darüber hinaus nutzen wir Ihre E-Mail-Adresse, um Ihnen unseren Newsletter zuzusenden, wenn Sie uns dazu Ihre vorherige ausdrückliche Einwilligung in den Erhalt eines Newsletters bzw. von Werbung erteilt haben. In diesem Fall verarbeiten wir Ihre E-Mail-Adresse, um Ihnen wunschgemäß den Newsletter zustellen zu können (Art. 6 Abs. 1 lit. b DSGVO). Der Verwendung Ihrer E-Mail-Adresse für solche Zwecke können Sie jederzeit schriftlich oder in Textform an hello@asideas.de oder Axel-Springer-Str. 65 in 10888 Berlin mit Wirkung für die Zukunft widersprechen, ohne dass hierfür andere als die Übermittlungskosten nach den Basistarifen entstehen.</p>
                    <p>Im Internet benötigt jedes Gerät zur Übertragung von Daten eine eindeutige Adresse, die sogenannte IP-Adresse. Die zumindest vorübergehende Speicherung der IP-Adresse ist technisch erforderlich, um eine Auslieferung der Website an den Rechner des Nutzers zu ermöglichen. Dabei kürzen wir die IP-Adressen vor jeglicher Verarbeitung und verarbeiten diese nur anonymisiert weiter. Es erfolgt keine Speicherung oder weitere Verarbeitung der ungekürzten IP-Adressen. Unsere Server speichern Ihre IP-Adresse außerdem für 14 Tage zu eigenen Sicherheitszwecken.</p>
                    <p>Wir bieten auf unserer Website und vereinzelt in Blogs eine Kommentarfunktion an, wobei zusätzliche personenbezogene Daten gespeichert werden, die Sie von sich aus angeben. Sofern Sie hierzu eine Einwilligung abgegeben haben, können Sie auf unserer Website in bestimmten Fällen Kommentare abgeben und abonnieren. Das gleiche gilt bei Umfragen, an denen Sie teilnehmen. Wenn Sie einen Kommentar veröffentlichen möchten, müssen Sie die hierfür vorgesehenen Felder ausfüllen. Sie können hierbei auch ein Pseudonym verwenden. Wenn Sie die Felder nicht ausfüllen, können Sie keinen Kommentar veröffentlichen. Wir erheben und verarbeiten die von Ihnen angegebenen Daten, um Ihren Kommentar wunschgemäß veröffentlichen zu können (Art. 6 Abs. 1 lit. b DSGVO). Insbesondere benötigen wir hierbei auch Ihre E-Mail-Adresse, um Sie im Falle von Beanstandungen Ihres Kommentars kontaktieren und Ihnen die Möglichkeit zur Stellungnahme geben zu können (Art. 6 Abs. 1 lit. c DSGVO).</p>
                    <p>Bei Verarbeitungsvorgängen, die von keiner oder mehreren der vorgenannten Rechtsgrundlagen erfasst werden, erfolgt die Verarbeitung, wenn sie zur Wahrung eines berechtigten Interesses erforderlich ist und aufgrund einer umfassenden Interessensabwägung Ihre Interessen, Grundrechte und Grundfreiheiten nicht überwiegen (Art. 6 Abs. 1 lit. f DSGVO). Ein berechtigtes Interesse ist anzunehmen, wenn die betroffene Person ein Kunde des Verantwortlichen ist. Basiert die Verarbeitung personenbezogener Daten hierauf ist unser berechtigtes Interesse insbesondere die Durchführung unserer Geschäftstätigkeit zugunsten des Wohlergehens all unserer Mitarbeiter und unserer Anteilseigner.</p>
                    <p>Unser berechtigtes Interesse, Ihnen maßgeschneiderte Produkte anbieten zu können, Sie über unsere Produkte, Neuerungen und Qualitätsmerkale zu informieren sowie unsere Services und Produkte stetig zu verbessern und dadurch auch unseren Umsatz zu steigern, ist die Rechtsgrundlage für die Verarbeitung zwecks Web/Appanalyse. Zu Webanalysediensten im Einzelnen siehe Ziffer 9.</p>
                    <p>Der Verarbeitung aufgrund eines berechtigten Interesses können Sie jederzeit widersprechen (siehe Ziffer 12.).</p>
                    <p>Für den Fall, dass die Daten zu einem anderen als bei der Datenerhebung angegebenen Zweck verarbeitet werden, erfolgt gemäß Art. 6 Abs. 4 DSGVO eine Kompatibilitätsprüfung. Eine Weiterverarbeitung ist dann nur zulässig, wenn der ursprüngliche Zweck mit dem neuen Zweck vereinbar oder aufgrund einer gesonderten Rechtsgrundlage erlaubt ist. Anerkannte kompatible Zwecke sind u. a. die Geltendmachung, Ausübung oder Verteidigung zivilrechtlicher Ansprüche sofern kein überwiegendes Interesse der betroffenen Person vorliegt. In diesem Fall werden wir Sie über die Zweckänderung informieren. Ist der neue Zweck nicht vereinbar mit dem bei Erhebung angegebenen Zweck, erfolgt eine neue Erhebung aufgrund einer neuen Rechtsgrundlage. Auch hier werden wir Sie über die Zweckänderung informieren.</p>
                    <h2>5. Ort der Verarbeitung</h2>
                    <p>Wir selbst übertragen Ihre personenbezogenen Daten nicht in Länder außerhalb des Europäischen Wirtschaftsraumes, außer in Fällen, in denen es nach der DSGVO zulässig ist. Ob Dritte, mit denen Sie eine eigene Vertragsbeziehung haben (wie z. B. mit Facebook, falls Sie einen Facebook-Account haben) Daten in Länder außerhalb des Europäischen Wirtschaftsraums übertragen, entzieht sich unserer Kenntnis und unserem Einfluss.</p>
                    <h2>6. Herkunft der Daten</h2>
                    <p>In bestimmten Fällen erhalten wir auch Daten, weil Sie in die Übermittlung an uns eingewilligt haben.</p>
                    <h2>7. Weitergabe Ihrer Daten an Dritte</h2>
                    <p>Wir übermitteln Ihre personenbezogenen Daten nur dann an Dritte, wenn die Übermittlung erforderlich ist, um unsere vertraglichen Verpflichtungen Ihnen gegenüber zu erfüllen und dies ersichtlich bei oder gemeinsam mit einem anderen Anbieter erfolgt (z. B. bei Kooperationen), wir zur Weitergabe in sonstiger Weise gesetzlich berechtigt oder verpflichtet sind, oder Sie uns eine entsprechende Einwilligung erteilt haben.</p>
                    <p>Zur Erbringung unserer Leistung können ausgewählte personenbezogene Daten innerhalb unseres Unternehmens an bestimmte Abteilungen mitgeteilt werden. Dazu gehören Mitarbeiter der Abteilungen Buchhaltung, Product Management, Marketing und IT.</p>
                    <p>In bestimmten Fällen setzen wir auch externe Dienstleister oder verbundene Unternehmen ein, die von uns beauftragt sind, Daten für uns weisungsgebunden zu verarbeiten. Solche Dienstleister werden von uns nach den strengen Vorgaben der DSGVO vertraglich als Auftragsverarbeiter verpflichtet und dürfen Ihre Daten zu keinen anderen Zwecken weiterverwenden. Von uns eingesetzte Auftragsverarbeiter erbringen für uns insbesondere die folgenden Dienstleistungen: Hosting, Newsletterversand und Web/Appanalyse.</p>

                    <p>Die Weitergabe von Daten an Auftragsverarbeiter erfolgt auf Grundlage von Art. 28 Abs. 1 DSGVO, hilfsweise auf Grundlage unseres berechtigten Interesses an den mit dem Einsatz von spezialisierten Auftragsverarbeitern verbundenen wirtschaftlichen und technischen Vorteilen, Art. 6 Abs. 1 lit. f DSGVO.</p>
                    <p>Sofern wir gesetzlich dazu verpflichtet sind oder dies datenschutzrechtlich erlaubt ist, übermitteln wir personenbezogene Daten an Behörden, zum Beispiel die Polizei oder Staatsanwaltschaft (Art. 6 Abs. 1 lit. c DSGVO). Die Weitergabe dieser Daten erfolgt auf Grundlage unseres berechtigten Interesses an der Bekämpfung von Missbrauch, der Verfolgung von Straftaten und der Sicherung, Geltendmachung und Durchsetzung von Ansprüchen und dass Ihre Rechte und Interessen am Schutz Ihrer personenbezogenen Daten nicht überwiegen, Art. 6 Abs. 1 lit. f DSGVO.</p>
                    <h2>8. Cookies und ähnliche Technologien</h2>
                    <p>Wir verwenden Cookies. Cookies sind kleine Dateien, die Ihr Browser auf Ihrem Gerät in einem dafür vorgesehenen Verzeichnis ablegt. Durch sie kann u. a. festgestellt werden, ob Sie eine Website schon einmal besucht haben. Sofern Sie zustimmen, können in Cookies auch Login-Daten für einen Onlinedienst gespeichert werden, so dass Sie diese Login-Daten nicht bei jedem Aufruf der Seite eingeben müssen. Viele Cookies enthalten eine sogenannte Cookie-ID. Eine Cookie-ID ist eine eindeutige Kennung des Cookies. Sie besteht aus einer Zeichenfolge, durch welche Websites und Server dem konkreten Internetbrowser zugeordnet werden können, in dem das Cookie gespeichert wurde. Dies ermöglicht es den besuchten Websites und Servern, den individuellen Browser der betroffenen Person von anderen Internetbrowsern, die andere Cookies enthalten, zu unterscheiden. Ein bestimmter Internetbrowser kann über die eindeutige Cookie-ID wiedererkannt und identifiziert werden.</p>
                    <p>Wir verwenden zwei Arten von Cookies. Zum einen technisch notwendige Cookies, ohne die die Funktionalität unserer Website eingeschränkt wäre sowie optionale Cookies, um unsere Website nutzerfreundlicher zu gestalten. Die durch technisch notwendige Cookies erhobenen Nutzerdaten werden nicht zur Erstellung von Nutzerprofilen verwendet. Die Verwendung der Analyse-Cookies erfolgt zu dem Zweck, die Qualität unserer Website und ihre Inhalte zu verbessern. Durch die Analyse-Cookies erfahren wir, wie die Website genutzt wird und können so unser Angebot stetig optimieren. Weitere Informationen zu den einzelnen Analysediensten finden Sie in Ziffer 9. dieser Datenschutzhinweise.</p>
                    <p>Werbeanzeigen werden zumeist durch Drittanbieter bereitgestellt. Diese nutzen möglicherweise und soweit durch Ihre Geräteeinstellungen zugelassen Informationen zu Ihren Besuchen, damit Anzeigen zu Produkten und Diensten geschaltet werden können, die Sie eventuell interessieren. Konkrete Kontaktdaten wie Ihr Name, Ihre Adresse, E-Mail-Adresse oder Telefonnummer werden dabei auf keinen Fall übertragen.</p>
                    <p>Sie können die Setzung von Cookies durch uns jederzeit mittels einer entsprechenden Einstellung des genutzten Internetbrowsers verhindern und damit der Setzung von Cookies dauerhaft widersprechen. Ferner können bereits gesetzte Cookies jederzeit über einen Internetbrowser oder andere Softwareprogramme gelöscht werden. Dies ist in allen gängigen Internetbrowsern möglich. Deaktivieren Sie die Setzung von Cookies in dem genutzten Internetbrowser, sind unter Umständen nicht alle Funktionen unserer Website vollumfänglich nutzbar.</p>
                    <p>Cookies können Sie als Person nicht identifizieren. In jedem Fall ist die Verwendung von Cookies auf Grundlage unseres berechtigten Interesses an einer bedarfsgerechten Gestaltung sowie der statistischen Auswertung von Axel Springer Ideas Engineering GmbH gerechtfertigt (Art. 6 Abs. 1 lit. f DSGVO).</p>
                    <h2>9. Soziale Netzwerke</h2>
                    <p>Sie finden uns auch in sozialen Netzwerken fremder Unternehmen, wie z. B. Facebook oder Twitter. Zudem haben wir einzelne Funktionen dieser Netzwerke auch in unsere Onlinedienste integriert. Beides können Sie allerdings nur nutzen, wenn Sie bei dem jeweiligen sozialen Netzwerk registriert und angemeldet sind. Bitte beachten Sie, dass für die Nutzung des jeweiligen sozialen Netzwerks die Nutzungs- und Datenschutzbedingungen dieses Unternehmens gelten, auf die wir keinen Einfluss haben. Wir erklären Ihnen aber gern, wie solche Netzwerke Ihre personenbezogenen Daten in diesem Zusammenhang verarbeiten:</p>
                    <p><b>Facebook</b><br/>
                        Wir haben auf dieser Website Komponenten des Unternehmens Facebook integriert. Facebook ist ein soziales Netzwerk.<br/>
                        Ein soziales Netzwerk ist ein im Internet betriebener sozialer Treffpunkt, eine Online-Gemeinschaft, die es den Nutzern in der Regel ermöglicht, untereinander zu kommunizieren und im virtuellen Raum zu interagieren. Ein soziales Netzwerk kann als Plattform zum Austausch von Meinungen und Erfahrungen dienen oder ermöglicht es der Internetgemeinschaft, persönliche oder unternehmensbezogene Informationen bereitzustellen. Facebook ermöglicht den Nutzern des sozialen Netzwerkes unter anderem die Erstellung von privaten Profilen, den Upload von Fotos und eine Vernetzung über Freundschaftsanfragen.<br/>
                        Betreibergesellschaft von Facebook ist die Facebook Inc., 1 Hacker Way, Menlo Park, CA 94025, USA. Für die Verarbeitung personenbezogener Daten Verantwortlicher ist, wenn eine betroffene Person außerhalb der USA oder Kanada lebt, die Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland.<br/>
                        Durch jeden Aufruf einer der Einzelseiten dieser Website, die durch uns betrieben wird und auf welcher eine Facebook-Komponente (Facebook-Plug-In) integriert wurde, wird der Internetbrowser auf dem informationstechnologischen System der betroffenen Person automatisch durch die jeweilige Facebook-Komponente veranlasst, eine Darstellung der entsprechenden Facebook-Komponente von Facebook herunterzuladen. Eine Gesamtübersicht über alle Facebook-Plug-Ins kann unter <a href="https://developers.facebook.com/docs/plugins/?locale=de_DE">https://developers.facebook.com/docs/plugins/?locale=de_DE</a> abgerufen werden. Im Rahmen dieses technischen Verfahrens erhält Facebook Kenntnis darüber, welche konkrete Unterseite unserer Website durch die betroffene Person besucht wird.<br/>
                        Sofern die betroffene Person gleichzeitig bei Facebook eingeloggt ist, erkennt Facebook mit jedem Aufruf unserer Website durch die betroffene Person und während der gesamten Dauer des jeweiligen Aufenthaltes auf unserer Website, welche konkrete Unterseite unserer Website die betroffene Person besucht. Diese Informationen werden durch die Facebook-Komponente gesammelt und durch Facebook dem jeweiligen Facebook-Account der betroffenen Person zugeordnet. Betätigt die betroffene Person einen der auf unserer Website integrierten Facebook-Buttons, beispielsweise den „Gefällt mir“-Button, oder gibt die betroffene Person einen Kommentar ab, ordnet Facebook diese Information dem persönlichen Facebook-Benutzerkonto der betroffenen Person zu und speichert diese personenbezogenen Daten.<br/>
                        Facebook erhält über die Facebook-Komponente immer dann eine Information darüber, dass die betroffene Person unsere Website besucht hat, wenn die betroffene Person zum Zeitpunkt des Aufrufs unserer Website gleichzeitig bei Facebook eingeloggt ist; dies findet unabhängig davon statt, ob die betroffene Person die Facebook-Komponente anklickt oder nicht. Ist eine derartige Übermittlung dieser Informationen an Facebook von der betroffenen Person nicht gewollt, kann diese die Übermittlung dadurch verhindern, dass sie sich vor einem Aufruf unserer Website aus ihrem Facebook-Account ausloggt.<br/>
                        Die von Facebook veröffentlichte Datenrichtlinie, die unter <a href="https://de-de.facebook.com/about/privacy/">https://de-de.facebook.com/about/privacy/</a> abrufbar ist, gibt Aufschluss über die Erhebung, Verarbeitung und Nutzung personenbezogener Daten durch Facebook. Ferner wird dort erläutert, welche Einstellungsmöglichkeiten Facebook zum Schutz der Privatsphäre der betroffenen Person bietet. Zudem sind unterschiedliche Applikationen erhältlich, die es ermöglichen, eine Datenübermittlung an Facebook zu unterdrücken. Solche Applikationen können durch die betroffene Person genutzt werden, um eine Datenübermittlung an Facebook zu unterdrücken.
                    </p>
                    <p><b>Instagram</b>
                        Wir setzen Komponenten des Dienstes Instagram ein. Instagram ist ein Dienst, der als audiovisuelle Plattform zu qualifizieren ist und den Nutzern das Teilen von Fotos und Videos und zudem eine Weiterverbreitung solcher Daten in anderen sozialen Netzwerken ermöglicht. Betreiber von Instagram ist die Instagram LLC, 1 Hacker Way, Building 14 First Floor, Menlo Park, CA, USA. Durch jeden Aufruf einer der Einzelseiten dieser Website, auf der eine Instagram-Komponente (Insta-Button) integriert wurde, erhält Instagram Kenntnis darüber, welche konkrete Unterseite unserer Website durch die betroffene Person besucht wird. Sofern Sie gleichzeitig bei Instagram eingeloggt sind, erkennt Instagram mit jedem Aufruf unserer Website und während der gesamten Dauer des jeweiligen Aufenthaltes auf unserer Website, welche konkrete Unterseite besucht wurde. Diese Informationen werden durch die Instagram-Komponente gesammelt und durch Instagram Ihrem Instagram-Account zugeordnet. Betätigen Sie einen der auf unserer Website integrierten Instagram-Buttons, werden die damit übertragenen Daten und Informationen dem persönlichen Instagram-Benutzerkonto zugeordnet und von Instagram gespeichert und verarbeitet. Instagram erhält über die Instagram-Komponente immer dann eine Information darüber, dass Sie unsere Website besucht haben, wenn Sie zum Zeitpunkt des Aufrufs unserer Website gleichzeitig bei Instagram eingeloggt sind; dies findet unabhängig davon statt, ob Sie die Instagram-Komponente anklickt oder nicht. Ist eine derartige Übermittlung dieser Informationen an Instagram von Ihnen nicht gewollt, kann diese die Übermittlung dadurch verhindern, dass Sie sich vor einem Aufruf unserer Website aus Ihrem Instagram-Account ausloggt. Weitere Informationen und die geltenden Datenschutzbestimmungen von Instagram können unter <a href="https://help.instagram.com/155833707900388">https://help.instagram.com/155833707900388</a> und <a href="https://www.instagram.com/about/legal/privacy/">https://www.instagram.com/about/legal/privacy/</a> abgerufen werden.
                    </p>
                    <p><b>LinkedIn</b><br/>
                        Wir haben auf dieser Website Komponenten der LinkedIn Corporation integriert. LinkedIn ist ein Internetbasiertes soziales Netzwerk, das eine Konnektierung der Nutzer mit bestehenden Geschäftskontakten sowie das Knüpfen von neuen Businesskontakten ermöglicht. Über 400 Millionen registrierte Personen nutzen LinkedIn in mehr als 200 Ländern. Damit ist LinkedIn derzeit die größte Plattform für Businesskontakte und eine der meistbesuchten Websites der Welt.<br/>
                        Betreibergesellschaft von LinkedIn ist die LinkedIn Corporation, 2029 Stierlin Court Mountain View, CA 94043, USA. Für Datenschutzangelegenheiten außerhalb der USA ist LinkedIn Ireland, Privacy Policy Issues, Wilton Plaza, Wilton Place, Dublin 2, Ireland, zuständig.<br/>
                        Bei jedem einzelnen Abruf unserer Website, die mit einer LinkedIn-Komponente (LinkedIn-Plug-In) ausgestattet ist, veranlasst diese Komponente, dass der von der betroffenen Person verwendete Browser eine entsprechende Darstellung der Komponente von LinkedIn herunterlädt. Weitere Informationen zu den LinkedIn-Plug-Ins können unter <a href="https://developer.linkedin.com/plugins">https://developer.linkedin.com/plugins</a> abgerufen werden. Im Rahmen dieses technischen Verfahrens erhält LinkedIn Kenntnis darüber, welche konkrete Unterseite unserer Website durch die betroffene Person besucht wird.<br/>
                        Sofern die betroffene Person gleichzeitig bei LinkedIn eingeloggt ist, erkennt LinkedIn mit jedem Aufruf unserer Website durch die betroffene Person und während der gesamten Dauer des jeweiligen Aufenthaltes auf unserer Website, welche konkrete Unterseite unserer Website die betroffene Person besucht. Diese Informationen werden durch die LinkedIn-Komponente gesammelt und durch LinkedIn dem jeweiligen LinkedIn-Account der betroffenen Person zugeordnet. Betätigt die betroffene Person einen auf unserer Website integrierten LinkedIn-Button, ordnet LinkedIn diese Information dem persönlichen LinkedIn-Benutzerkonto der betroffenen Person zu und speichert diese personenbezogenen Daten.<br/>
                        LinkedIn erhält über die LinkedIn-Komponente immer dann eine Information darüber, dass die betroffene Person unsere Website besucht hat, wenn die betroffene Person zum Zeitpunkt des Aufrufes unserer Website gleichzeitig bei LinkedIn eingeloggt ist; dies findet unabhängig davon statt, ob die betroffene Person die LinkedIn-Komponente anklickt oder nicht. Ist eine derartige Übermittlung dieser Informationen an LinkedIn von der betroffenen Person nicht gewollt, kann diese die Übermittlung dadurch verhindern, dass sie sich vor einem Aufruf unserer Website aus ihrem LinkedIn-Account ausloggt.<br/>
                        LinkedIn bietet unter <a href="https://www.linkedin.com/psettings/guest-controls">https://www.linkedin.com/psettings/guest-controls</a> die Möglichkeit, E-Mail-Nachrichten, SMS-Nachrichten und zielgerichtete Anzeigen abzubestellen sowie Anzeigen-Einstellungen zu verwalten. LinkedIn nutzt ferner Partner wie Quantcast, Google Analytics, BlueKai, DoubleClick, Nielsen, Comscore, Eloqua und Lotame, die Cookies setzen können. Solche Cookies können unter <a href="https://www.linkedin.com/legal/cookie-policy">https://www.linkedin.com/legal/cookie-policy</a> abgelehnt werden. Die geltenden Datenschutzbestimmungen von LinkedIn sind unter <a href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a> abrufbar. Die Cookie-Richtlinie von LinkedIn ist unter <a href="https://www.linkedin.com/legal/cookie-policy">https://www.linkedin.com/legal/cookie-policy</a> abrufbar.
                    </p>
                    <p><b>Twitter</b><br/>
                        Wir haben auf dieser Website Komponenten von Twitter integriert. Twitter ist ein multilingualer öffentlich zugänglicher Mikroblogging-Dienst, auf welchem die Nutzer sogenannte Tweets, also Kurznachrichten, die auf 140 Zeichen begrenzt sind, veröffentlichen und verbreiten können. Diese Kurznachrichten sind für jedermann, also auch für nicht bei Twitter angemeldete Personen abrufbar. Die Tweets werden aber auch den sogenannten Followern des jeweiligen Nutzers angezeigt. Follower sind andere Twitter-Nutzer, die den Tweets eines Nutzers folgen. Ferner ermöglicht Twitter über Hashtags, Verlinkungen oder Retweets die Ansprache eines breiten Publikums.<br/>
                        Betreibergesellschaft von Twitter ist die Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA.<br/>
                        Durch jeden Aufruf einer der Einzelseiten dieser Website, die durch den für uns betrieben wird und auf welcher eine Twitter-Komponente (Twitter-Button) integriert wurde, wird der Internetbrowser auf dem informationstechnologischen System der betroffenen Person automatisch durch die jeweilige Twitter-Komponente veranlasst, eine Darstellung der entsprechenden Twitter-Komponente von Twitter herunterzuladen. Weitere Informationen zu den Twitter-Buttons sind unter <a href="https://about.twitter.com/de/resources/buttons">https://about.twitter.com/de/resources/buttons</a> abrufbar. Im Rahmen dieses technischen Verfahrens erhält Twitter Kenntnis darüber, welche konkrete Unterseite unserer Website durch die betroffene Person besucht wird. Zweck der Integration der Twitter-Komponente ist es, unseren Nutzern eine Weiterverbreitung der Inhalte diese Website zu ermöglichen, diese Website in der digitalen Welt bekannt zu machen und unsere Besucherzahlen zu erhöhen.<br/>
                        Sofern die betroffene Person gleichzeitig bei Twitter eingeloggt ist, erkennt Twitter mit jedem Aufruf unserer Website durch die betroffene Person und während der gesamten Dauer des jeweiligen Aufenthaltes auf unserer Website, welche konkrete Unterseite unserer Website die betroffene Person besucht. Diese Informationen werden durch die Twitter-Komponente gesammelt und durch Twitter dem jeweiligen Twitter-Account der betroffenen Person zugeordnet. Betätigt die betroffene Person einen der auf unserer Website integrierten Twitter-Buttons, werden die damit übertragenen Daten und Informationen dem persönlichen Twitter-Benutzerkonto der betroffenen Person zugeordnet und von Twitter gespeichert und verarbeitet.<br/>
                        Twitter erhält über die Twitter-Komponente immer dann eine Information darüber, dass die betroffene Person unsere Website besucht hat, wenn die betroffene Person zum Zeitpunkt des Aufrufs unserer Website gleichzeitig bei Twitter eingeloggt ist; dies findet unabhängig davon statt, ob die betroffene Person die Twitter-Komponente anklickt oder nicht. Ist eine derartige Übermittlung dieser Informationen an Twitter von der betroffenen Person nicht gewollt, kann diese die Übermittlung dadurch verhindern, dass sie sich vor einem Aufruf unserer Website aus ihrem Twitter-Account ausloggt.<br/>
                        Die geltenden Datenschutzbestimmungen von Twitter sind unter <a href="https://twitter.com/privacy?lang=de">https://twitter.com/privacy?lang=de</a> abrufbar.
                    </p>
                    <p><b>Xing</b><br/>
                        Wir haben auf dieser Website Komponenten von Xing integriert. Xing ist ein Internetbasiertes soziales Netzwerk, das die Konnektierung der Nutzer mit bestehenden Geschäftskontakten sowie das Knüpfen von neuen Businesskontakten ermöglicht. Die einzelnen Nutzer können bei Xing ein persönliches Profil von sich anlegen. Unternehmen können beispielsweise Unternehmensprofile erstellen oder Stellenangebote auf Xing veröffentlichen.<br/>
                        Betreibergesellschaft von Xing ist die XING SE, Dammtorstraße 30, 20354 Hamburg, Deutschland.<br/>
                        Durch jeden Aufruf einer der Einzelseiten dieser Website, die durch den für die uns betrieben wird und auf welcher eine Xing-Komponente (Xing-Plug-In) integriert wurde, wird der Internetbrowser auf dem informationstechnologischen System der betroffenen Person automatisch durch die jeweilige Xing-Komponente veranlasst, eine Darstellung der entsprechenden Xing-Komponente von Xing herunterzuladen. Weitere Informationen zum den Xing-Plug-Ins können unter <a href="https://dev.xing.com/plugins">https://dev.xing.com/plugins</a> abgerufen werden. Im Rahmen dieses technischen Verfahrens erhält Xing Kenntnis darüber, welche konkrete Unterseite unserer Website durch die betroffene Person besucht wird.<br/>
                        Sofern die betroffene Person gleichzeitig bei Xing eingeloggt ist, erkennt Xing mit jedem Aufruf unserer Website durch die betroffene Person und während der gesamten Dauer des jeweiligen Aufenthaltes auf unserer Website, welche konkrete Unterseite unserer Website die betroffene Person besucht. Diese Informationen werden durch die Xing-Komponente gesammelt und durch Xing dem jeweiligen Xing-Account der betroffenen Person zugeordnet. Betätigt die betroffene Person einen der auf unserer Website integrierten Xing-Buttons, beispielsweise den „Share“-Button, ordnet Xing diese Information dem persönlichen Xing-Benutzerkonto der betroffenen Person zu und speichert diese personenbezogenen Daten.<br/>
                        Xing erhält über die Xing-Komponente immer dann eine Information darüber, dass die betroffene Person unsere Website besucht hat, wenn die betroffene Person zum Zeitpunkt des Aufrufs unserer Website gleichzeitig bei Xing eingeloggt ist; dies findet unabhängig davon statt, ob die betroffene Person die Xing-Komponente anklickt oder nicht. Ist eine derartige Übermittlung dieser Informationen an Xing von der betroffenen Person nicht gewollt, kann diese die Übermittlung dadurch verhindern, dass sie sich vor einem Aufruf unserer Website aus ihrem Xing-Account ausloggt.<br/>
                        Die von Xing veröffentlichten Datenschutzbestimmungen, die unter <a href="https://www.xing.com/privacy">https://www.xing.com/privacy</a> abrufbar sind, geben Aufschluss über die Erhebung, Verarbeitung und Nutzung personenbezogener Daten durch Xing. Ferner hat Xing unter <a href="https://www.xing.com/app/share?op=data_protection Datenschutzhinweise">https://www.xing.com/app/share?op=data_protection Datenschutzhinweise</a> für den XING-Share-Button veröffentlicht.
                    </p>
                    <p>Auf Smartphones und Tablets werden die vorgenannten Services häufig nicht durch Plug-ins umgesetzt, sondern durch eine geräteinterne „Teilen“-Funktion. Entsprechend dessen Einstellungen können Informationen auch an weitere Social-Media-Dienstleister gegeben werden. Bitte entnehmen Sie Details hierzu Ihren Geräteinformationen.</p>
                    <h2>10. Sonstige Dienste</h2>
                    <p>Weitere Dienste, die wir verwenden sind:</p>
                    <p><b>Disqus-Kommentierungsfunktion</b><br/>
                        Diese Website benutzt die DISQUS-Kommentierungsfunktion, die von der Disqus Inc., 301 Howard Street, Suite 300, San Francisco, CA 94105, USA (im Folgenden als "Disqus" bezeichnet), bereitgestellt wird. Disqus ist ein interaktives Kommentarsystem, das es dem registrierten Nutzer ermöglicht, mit nur einer Anmeldung auf jeder Website, die Disqus einsetzt, zu kommentieren. Disqus erlaubt die Anmeldung über bestehende Accounts bei Facebook (über Facebook Connect), Twitter und Google+. Wenn Sie sich über Ihren Facebook-, Twitter-, Google+-Account anmelden, werden auch von diesen Anbietern möglicherweise Daten erhoben, gespeichert und genutzt. Einzelheiten dazu finden Sie in den Datenschutzbestimmungen des jeweiligen Anbieters. Die Nutzung der Kommentierungsfunktion ist auch als "Gast" ohne Registrierung möglich. Allerdings stehen dann einige Funktionen nicht zur Verfügung.<br/>
                        Disqus übermittelt neben dem Kommentartext Ihre E-Mail-Adresse und IP-Adresse an uns. Den Kommentartext benötigen wir, um diesen veröffentlichen zu können. Die anderen Informationen benötigen wir ausschließlich für den Zweck der Kontaktaufnahme im Zusammenhang mit Ihrer Nutzung von DISQUS, beispielsweise wenn wir Rückfragen zu Ihrem Nutzerkommentar haben oder zur Vermeidung von Haftung und Missbrauch. Um eine Haftung für Kommentarinhalte zu vermeiden, kann es für uns auch erforderlich sein, Kommentare zu löschen, von der Veröffentlichung auszuschließen oder – als mildere Maßnahme und mit entsprechender Kennzeichnung – zu bearbeiten.<br/>
                        Hinsichtlich der Erhebung, Verarbeitung und Nutzung der betreffenden Daten durch DISQUS sowie zu Ihren Rechten diesbezüglich gelten die Nutzungsbedingungen und Datenschutzhinweise von DISQUS, abrufbar unter <a href="http://docs.disqus.com/help/30/">http://docs.disqus.com/help/30/</a> und <a href="http://docs.disqus.com/help/29/">http://docs.disqus.com/help/29/</a>.
                    </p>
                    <h2>11. Speicherdauer</h2>
                    <p>Wir speichern personenbezogene Daten nur solange wir dazu berechtigt sind und der Verarbeitungszweck nicht entfallen ist. Für die Dauer der Speicherung von personenbezogenen Daten gilt die jeweilige gesetzliche Aufbewahrungsfrist. Nach Ablauf der Frist werden die entsprechenden Daten routinemäßig gelöscht, sofern sie nicht mehr zur Vertragserfüllung oder Vertragsanbahnung erforderlich sind.</p>
                    <h2>12. Kontaktdaten und Ihre Rechte als betroffene Person</h2>
                    <p>Bitte wenden Sie sich bei Fragen und Anregungen zum Datenschutz sowie zur Durchsetzung Ihrer Rechte als betroffene Person jederzeit an unseren Datenschutzbeauftragten:</p>
                    <p>Axel Springer SE<br/>
                        Datenschutz<br/>
                        Axel-Springer-Str. 65<br/>
                        10888 Berlin<br/>
                        datenschutz@axelspringer.de</p>
                    <p>▫ <b>Auskunft und Berichtigung</b></p>
                    <p>Sie können von uns jederzeit unentgeltlich Auskunft darüber erhalten, ob personenbezogene Daten zu Ihrer Person von uns verarbeitet werden und auch konkret welche Daten über sie gespeichert werden sowie eine Kopie der gespeicherten Daten verlangen. Sie können ferner unrichtige Daten berichtigen und vervollständigen lassen.</p>
                    <p>▫ <b>Löschung, Einschränkung und das Recht auf Vergessenwerden</b></p>
                    <p>Sie können die Löschung und Einschränkung Ihrer personenbezogenen Daten verlangen. Bitte beachten Sie, dass es z. B. für entgeltliche Verträge wie dem Kauf eines Abonnements von Axel Springer Ideas Engineering GmbH gesetzliche Aufbewahrungspflichten gibt und wir daher Ihre Daten nicht in jedem Fall vollständig löschen dürfen. In diesem Fall werden Ihre Daten mit dem Ziel markiert, ihre künftige Verarbeitung einzuschränken.</p>
                    <p>▫ <b>Datenübertragbarkeit</b></p>
                    <p>Sofern anwendbar haben Sie außerdem das Recht, dass die sie betreffenden personenbezogenen Daten in einem strukturierten, gängigen und maschinenlesbaren Format an Sie oder einen anderen Verantwortlichen übermittelt werden, sofern die Verarbeitung auf der Einwilligung oder einem Vertrag beruht und mithilfe automatisierter Verfahren erfolgt. Dies gilt jedoch nicht, sofern die Verarbeitung nicht für die Wahrnehmung einer Aufgabe erforderlich ist, die im öffentlichen Interesse liegt oder in Ausübung öffentlicher Gewalt erfolgt, welche dem Verantwortlichen übertragen wurde. Ferner haben Sie das Recht, zu erwirken, dass die personenbezogenen Daten direkt von einem Verantwortlichen an einen anderen Verantwortlichen übermittelt werden, soweit dies technisch machbar ist und sofern hiervon nicht die Rechte und Freiheiten anderer Personen beeinträchtigt werden.</p>
                    <p>▫ <b>Widerruf / Widerspruch </b></p>
                    <p>
                        <table className="tableStyle">
                            <tr>
                                <td>Ihre abgegebenen Einwilligungen können Sie jederzeit mit Wirkung für die Zukunft unter der o. g. Kontaktadresse widerrufen. Insbesondere können Sie der Verwendung Ihrer E-Mail-Adresse zum Zwecke des Newsletterversandes jederzeit schriftlich oder in Textform an hello@asideas.de oder Axel-Springer-Str. 65 in 10888 Berlin mit Wirkung für die Zukunft widersprechen, ohne dass hierfür andere als die Übermittlungskosten nach den Basistarifen entstehen. Ferner haben Sie das Recht aus Gründen, die sich aus Ihrer besonderen Situation ergeben, jederzeit gegen die Verarbeitung Sie betreffender personenbezogener Daten, die aufgrund eines berechtigten oder öffentlichen Interesses erfolgt, Widerspruch einzulegen. Dies gilt auch für ein auf diese Bestimmungen gestütztes Profiling. Wir verarbeiten die personenbezogenen Daten im Falle des Widerspruchs nicht mehr, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die den Interessen, Rechten und Freiheiten der betroffenen Person überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.<br/>
                                    <br/>
                                    Sofern wir personenbezogene Daten verarbeiten, um Direktwerbung zu betreiben, so haben Sie das Recht, jederzeit Widerspruch gegen die Verarbeitung der personenbezogenen Daten zum Zwecke derartiger Werbung unter der. o. g. Kontaktadresse einzulegen. Dies gilt auch für das Profiling, soweit es mit solcher Direktwerbung in Verbindung steht. Zudem haben Sie das Recht, aus Gründen, die sich aus Ihrer besonderen Situation ergeben, gegen die Sie betreffende Verarbeitung personenbezogener Daten, die bei uns zu wissenschaftlichen oder historischen Forschungszwecken oder zu statistischen Zwecken erfolgen, Widerspruch einzulegen, es sei denn, eine solche Verarbeitung ist zur Erfüllung einer im öffentlichen Interesse liegenden Aufgabe erforderlich.
                                </td>
                            </tr>
                        </table>
                    </p>
                    <p>▫ <b>Beschwerderecht</b></p>
                    <p>Ferner haben Sie ein Beschwerderecht bei der zuständigen Aufsichtsbehörde sowie die Möglichkeit Rechtsbehelfe einzulegen. Die Aufsichtsbehörde, bei der die Beschwerde eingereicht wurde, unterrichtet den Beschwerdeführer über den Stand und die Ergebnisse der Beschwerde einschließlich der Möglichkeit eines gerichtlichen Rechtsbehelfs.</p>
                    <p>▫ <b>Bestehen einer automatisierten Entscheidungsfindung</b></p>
                    <p>Wir verzichten auf eine automatische Entscheidungsfindung oder ein Profiling.</p>
                    <p><b>Stand:</b> 25. Mai 2018</p>
                </div>
            </section>
        );
    }
}
